/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPresentacion;

import capaNegocio.clsDepartamento;
import capaNegocio.clsDistrito;
import capaNegocio.clsProvincia;
import capaNegocio.clsUsuario;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * INTEGRANTES: - Ching Ayacila, Jonatan - Chapoñan Paico, Jesus - Pupuche
 * Adrianzen, Rodrigho
 *
 */
public class FrmRegistrarse extends javax.swing.JFrame {

    private clsUsuario usuario;
    private Map<String, Integer> mapDepartamentos = new HashMap<>();
    private Map<String, Integer> mapProvincias = new HashMap<>();
    private Map<String, Integer> mapDistritos = new HashMap<>();

    /**
     * Creates new form FrmRegistrarse
     */
    public FrmRegistrarse() {
        initComponents();
        usuario = new clsUsuario();
        cargarDepartamentos();
    }

    private void cargarDepartamentos() {
        try {
            clsDepartamento depto = new clsDepartamento();
            ResultSet rs = depto.obtenerDepartamentos();

            cboDepartamento.removeAllItems();  // Limpiar el ComboBox
            mapDepartamentos.clear();  // Limpiar el mapa

            while (rs.next()) {
                String nombreDepartamento = rs.getString("nombre");
                int idDepartamento = rs.getInt("idDpto");

                // Agregar el nombre al ComboBox
                cboDepartamento.addItem(nombreDepartamento);

                // Agregar el nombre y el ID al mapa
                mapDepartamentos.put(nombreDepartamento, idDepartamento);
            }
            rs.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar departamentos: " + ex.getMessage());
        }
    }

    private void cargarProvincias(int idDpto) {
        cboProvincia.removeAllItems();  // Limpiar el ComboBox
        mapProvincias.clear();  // Limpiar el mapa

        try {
            clsProvincia prov = new clsProvincia();
            ResultSet rs = prov.obtenerProvinciasPorDepartamento(idDpto);
            while (rs.next()) {
                String nombreProvincia = rs.getString("nombre");
                int idProvincia = rs.getInt("idProvincia");

                // Agregar el nombre al ComboBox
                cboProvincia.addItem(nombreProvincia);

                // Agregar el nombre y el ID al mapa
                mapProvincias.put(nombreProvincia, idProvincia);
            }
            rs.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar provincias: " + ex.getMessage());
        }
    }

    private void cargarDistritos(int idProvincia) {
        cboDistrito.removeAllItems();  // Limpiar el ComboBox
        mapDistritos.clear();  // Limpiar el mapa

        try {
            clsDistrito dist = new clsDistrito();
            ResultSet rs = dist.obtenerDistritosPorProvincia(idProvincia);
            while (rs.next()) {
                String nombreDistrito = rs.getString("nombre");
                int idDistrito = rs.getInt("idDistrito");

                // Agregar el nombre al ComboBox
                cboDistrito.addItem(nombreDistrito);

                // Agregar el nombre y el ID al mapa
                mapDistritos.put(nombreDistrito, idDistrito);
            }
            rs.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar distritos: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        lblNroDoc = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtApellido = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtNroDoc = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtContraseña = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtCelular = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        cboDepartamento = new javax.swing.JComboBox<>();
        jcFechaNac = new com.toedter.calendar.JDateChooser();
        cboTipoDoc = new javax.swing.JComboBox<>();
        lblProvincia = new javax.swing.JLabel();
        cboProvincia = new javax.swing.JComboBox<>();
        lblGenero = new javax.swing.JLabel();
        cboDistrito = new javax.swing.JComboBox<>();
        lblDistrito = new javax.swing.JLabel();
        rbMujer = new javax.swing.JRadioButton();
        rbHombre = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        lblIniciarSesion = new javax.swing.JLabel();
        lblIniciarSesion1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrarse");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        lblFechaNacimiento.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblFechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaNacimiento.setText("Fecha Nacimiento:");
        jPanel1.add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("Email:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblApellido.setBackground(new java.awt.Color(255, 255, 255));
        lblApellido.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(0, 0, 0));
        lblApellido.setText("Apellidos:");
        jPanel1.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        lblDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        lblDepartamento.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        lblDepartamento.setText("Departamento:");
        jPanel1.add(lblDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        lblNroDoc.setBackground(new java.awt.Color(255, 255, 255));
        lblNroDoc.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblNroDoc.setForeground(new java.awt.Color(0, 0, 0));
        lblNroDoc.setText("Nro Documento:");
        jPanel1.add(lblNroDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        lblContraseña.setBackground(new java.awt.Color(255, 255, 255));
        lblContraseña.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(0, 0, 0));
        lblContraseña.setText("Contraseña:");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        lblCelular.setBackground(new java.awt.Color(255, 255, 255));
        lblCelular.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(0, 0, 0));
        lblCelular.setText("Celular:");
        jPanel1.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        btnRegistrarse.setBackground(new java.awt.Color(164, 48, 51));
        btnRegistrarse.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("REGISTRARSE");
        btnRegistrarse.setToolTipText("");
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 710, 36));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setText("Ingresar Email");
        txtEmail.setBorder(null);
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 320, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 320, 10));

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombre.setText("Ingresar Nombre Completo");
        txtNombre.setBorder(null);
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 320, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 320, 10));

        txtApellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtApellido.setText("Ingresar Apellido Completo");
        txtApellido.setBorder(null);
        txtApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMouseClicked(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 320, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 320, 10));

        txtNroDoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNroDoc.setText("Nro de documento");
        txtNroDoc.setBorder(null);
        txtNroDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNroDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNroDocMouseClicked(evt);
            }
        });
        jPanel1.add(txtNroDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 210, 30));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 210, 10));

        txtContraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtContraseña.setText("Ingresar Contraseña");
        txtContraseña.setBorder(null);
        txtContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseClicked(evt);
            }
        });
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 320, 30));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 320, 10));

        txtCelular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCelular.setText("Ingresar Celular");
        txtCelular.setBorder(null);
        txtCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCelularMouseClicked(evt);
            }
        });
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 320, 30));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 320, 10));

        cboDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        cboDepartamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDepartamentoActionPerformed(evt);
            }
        });
        jPanel1.add(cboDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 200, 30));

        jcFechaNac.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jcFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 320, 30));

        cboTipoDoc.setBackground(new java.awt.Color(255, 255, 255));
        cboTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Pasaporte", "Carnet Extranjeria" }));
        cboTipoDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cboTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 100, 30));

        lblProvincia.setBackground(new java.awt.Color(255, 255, 255));
        lblProvincia.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblProvincia.setForeground(new java.awt.Color(0, 0, 0));
        lblProvincia.setText("Provincia:");
        jPanel1.add(lblProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        cboProvincia.setBackground(new java.awt.Color(255, 255, 255));
        cboProvincia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProvinciaActionPerformed(evt);
            }
        });
        jPanel1.add(cboProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 210, 30));

        lblGenero.setBackground(new java.awt.Color(255, 255, 255));
        lblGenero.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(0, 0, 0));
        lblGenero.setText("Género:");
        jPanel1.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        cboDistrito.setBackground(new java.awt.Color(255, 255, 255));
        cboDistrito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDistritoActionPerformed(evt);
            }
        });
        jPanel1.add(cboDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 220, 30));

        lblDistrito.setBackground(new java.awt.Color(255, 255, 255));
        lblDistrito.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblDistrito.setForeground(new java.awt.Color(0, 0, 0));
        lblDistrito.setText("Distrito:");
        jPanel1.add(lblDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));

        rbMujer.setBackground(new java.awt.Color(255, 255, 255));
        rbMujer.setForeground(new java.awt.Color(0, 0, 0));
        rbMujer.setText("MUJER");
        jPanel1.add(rbMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        rbHombre.setBackground(new java.awt.Color(255, 255, 255));
        rbHombre.setForeground(new java.awt.Color(0, 0, 0));
        rbHombre.setText("HOMBRE");
        jPanel1.add(rbHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 800, 600));

        jPanel2.setBackground(new java.awt.Color(164, 48, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(164, 48, 51));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar2.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 35, 34));

        lblIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion.setFont(new java.awt.Font("Candara Light", 1, 42)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion.setText("REGISTRARSE");
        jPanel2.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        lblIniciarSesion1.setBackground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion1.setFont(new java.awt.Font("Candara Light", 1, 42)); // NOI18N
        lblIniciarSesion1.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion1.setText("REGISTRO");
        jPanel2.add(lblIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        try {
            String nombre = txtNombre.getText();
            String apellidos = txtApellido.getText();
            String email = txtEmail.getText();
            String celular = txtCelular.getText();
            String contraseña = txtContraseña.getText();
            String tipoDocIdentidad = (String) cboTipoDoc.getSelectedItem(); // Si es un ComboBox
            String nroDocIdentidad = txtNroDoc.getText();
            int idDistrito = mapDistritos.get((String) cboDistrito.getSelectedItem()); // Map del distrito seleccionado
            String sexo = rbHombre.isSelected() ? "HOMBRE" : "MUJER"; // Radiobutton para seleccionar sexo
            Date fechaNac = jcFechaNac.getDate(); // Obtener la fecha desde el date chooser

            // Instancia de la clase clsUsuario
            clsUsuario usuario = new clsUsuario();

            // Llamar al método para registrar al usuario
            usuario.registrarUsuario(nombre, apellidos, email, celular, contraseña, tipoDocIdentidad, nroDocIdentidad,
                    idDistrito, sexo, fechaNac);

            JOptionPane.showMessageDialog(null, "Usuario registrado correctamente");
            this.dispose();

            FrmIniciarSesion objInicio = new FrmIniciarSesion();
            objInicio.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al registrar el usuario: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        txtNombre.setText("");
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMouseClicked
        txtApellido.setText("");
    }//GEN-LAST:event_txtApellidoMouseClicked

    private void txtNroDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNroDocMouseClicked
        txtNroDoc.setText("");
    }//GEN-LAST:event_txtNroDocMouseClicked

    private void txtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseClicked
        txtContraseña.setText("");
    }//GEN-LAST:event_txtContraseñaMouseClicked

    private void txtCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCelularMouseClicked
        txtCelular.setText("");
    }//GEN-LAST:event_txtCelularMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void cboDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDepartamentoActionPerformed
        String selectedDepartamento = (String) cboDepartamento.getSelectedItem();

        // Obtener el ID del departamento seleccionado desde el mapa
        if (selectedDepartamento != null && mapDepartamentos.containsKey(selectedDepartamento)) {
            int idDpto = mapDepartamentos.get(selectedDepartamento);
            cargarProvincias(idDpto);  // Cargar las provincias correspondientes
        }
    }//GEN-LAST:event_cboDepartamentoActionPerformed

    private void cboProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProvinciaActionPerformed
        String selectedProvincia = (String) cboProvincia.getSelectedItem();

        // Obtener el ID de la provincia seleccionada desde el mapa
        if (selectedProvincia != null && mapProvincias.containsKey(selectedProvincia)) {
            int idProvincia = mapProvincias.get(selectedProvincia);
            cargarDistritos(idProvincia);  // Cargar los distritos correspondientes
        }
    }//GEN-LAST:event_cboProvinciaActionPerformed

    private void cboDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDistritoActionPerformed
        String selectedDistrito = (String) cboDistrito.getSelectedItem();

        // Obtener el ID del distrito seleccionado desde el mapa
        if (selectedDistrito != null && mapDistritos.containsKey(selectedDistrito)) {
            int idDistrito = mapDistritos.get(selectedDistrito);
            // Aquí puedes hacer lo que necesites con el ID del distrito
        }
    }//GEN-LAST:event_cboDistritoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JComboBox<String> cboDepartamento;
    private javax.swing.JComboBox<String> cboDistrito;
    private javax.swing.JComboBox<String> cboProvincia;
    private javax.swing.JComboBox<String> cboTipoDoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private com.toedter.calendar.JDateChooser jcFechaNac;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblDistrito;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblIniciarSesion1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNroDoc;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroDoc;
    // End of variables declaration//GEN-END:variables
}
