/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package capaPresentacion;

import capaNegocio.clsGeneroPelicula;
import capaNegocio.clsPelicula;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * INTEGRANTES: - Ching Ayacila, Jonatan - Chapoñan Paico, Jesus - Pupuche
 * Adrianzen, Rodrigho
 *
 */
public class jdManPelicula extends javax.swing.JDialog {

    private Map<String, Integer> mapGeneros = new HashMap<>();

    public jdManPelicula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        cargarGeneros();
    }

    private void cargarGeneros() {
        try {
            clsGeneroPelicula generoPelicula = new clsGeneroPelicula();
            ResultSet rs = generoPelicula.obtenerGeneros();
            cboGenero.removeAllItems();
            mapGeneros.clear();

            while (rs.next()) {
                String nombreGenero = rs.getString("nombre");
                int idGenero = rs.getInt("idGenero");

                cboGenero.addItem(nombreGenero);
                mapGeneros.put(nombreGenero, idGenero);
            }
            rs.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar géneros: " + ex.getMessage());
        }
    }


    private void limpiarCampos() {
        txtId.setText("");
        txtNombre.setText("");
        cboGenero.setSelectedIndex(-1);
        spnDuracion.setValue(0);
        txtApto.setText("");
        txtSipnosis.setText("");
        txtDirector.setText("");
        chkVigente.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIniciarSesion1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        cboGenero = new javax.swing.JComboBox<>();
        lblDepartamento = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblNombre2 = new javax.swing.JLabel();
        spnDuracion = new javax.swing.JSpinner();
        lblNombre3 = new javax.swing.JLabel();
        lblNombre4 = new javax.swing.JLabel();
        lblNombre5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSipnosis = new javax.swing.JTextArea();
        lblNombre6 = new javax.swing.JLabel();
        txtDirector = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblNombre7 = new javax.swing.JLabel();
        chkVigente = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        txtApto = new javax.swing.JTextField();
        lblNombre8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPeliculas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(164, 48, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion1.setBackground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion1.setFont(new java.awt.Font("Candara Light", 1, 42)); // NOI18N
        lblIniciarSesion1.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion1.setText("MANTENIMIENTO PELICULA");
        jPanel1.add(lblIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Horas");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        cboGenero.setBackground(new java.awt.Color(255, 255, 255));
        cboGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(cboGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 200, 30));

        lblDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        lblDepartamento.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        lblDepartamento.setText("Género:");
        jPanel2.add(lblDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombre.setText("Ingresar Nombre De Pelicula");
        txtNombre.setBorder(null);
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 320, 10));

        lblNombre2.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblNombre2.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre2.setText("ID:");
        jPanel2.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        spnDuracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(spnDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 110, 30));

        lblNombre3.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblNombre3.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre3.setText("Sipnosis:");
        jPanel2.add(lblNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        lblNombre4.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblNombre4.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre4.setText("Duración:");
        jPanel2.add(lblNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblNombre5.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblNombre5.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre5.setText("Vigente:");
        jPanel2.add(lblNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        txtSipnosis.setColumns(20);
        txtSipnosis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSipnosis.setRows(5);
        txtSipnosis.setText("Ingresar Sipnosis");
        txtSipnosis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSipnosis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSipnosisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtSipnosis);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 310, 100));

        lblNombre6.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblNombre6.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre6.setText("Apto:");
        jPanel2.add(lblNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        txtDirector.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDirector.setText("Ingresar Director");
        txtDirector.setBorder(null);
        txtDirector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDirector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDirectorMouseClicked(evt);
            }
        });
        jPanel2.add(txtDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 230, 30));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 230, 10));

        lblNombre7.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre7.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblNombre7.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre7.setText("Director:");
        jPanel2.add(lblNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        chkVigente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chkVigente.setForeground(new java.awt.Color(0, 0, 0));
        chkVigente.setText("VIgente");
        jPanel2.add(chkVigente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 260, 10));

        txtApto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtApto.setText("Ingresar Apto Para");
        txtApto.setBorder(null);
        txtApto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtApto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAptoMouseClicked(evt);
            }
        });
        jPanel2.add(txtApto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 260, 30));

        lblNombre8.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre8.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lblNombre8.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre8.setText("Nombre:");
        jPanel2.add(lblNombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtId.setBorder(null);
        txtId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, 30));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, 10));

        jButton5.setText("BUSCAR");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 410, 650));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPeliculas);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 420));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 520, 480));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel4.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jButton2.setText("MODIFICAR");
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jButton3.setText("ELIMINAR");
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jButton4.setText("DAR BAJA");
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 520, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        txtNombre.setText("");
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtDirectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDirectorMouseClicked
        txtDirector.setText("");
    }//GEN-LAST:event_txtDirectorMouseClicked

    private void txtSipnosisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSipnosisMouseClicked
        txtSipnosis.setText("");
    }//GEN-LAST:event_txtSipnosisMouseClicked

    private void txtAptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAptoMouseClicked
        txtApto.setText("");
    }//GEN-LAST:event_txtAptoMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboGenero;
    private javax.swing.JCheckBox chkVigente;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblIniciarSesion1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombre4;
    private javax.swing.JLabel lblNombre5;
    private javax.swing.JLabel lblNombre6;
    private javax.swing.JLabel lblNombre7;
    private javax.swing.JLabel lblNombre8;
    private javax.swing.JSpinner spnDuracion;
    private javax.swing.JTable tblPeliculas;
    private javax.swing.JTextField txtApto;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtSipnosis;
    // End of variables declaration//GEN-END:variables
}
